-- Upflow runtime baseline schema (Supabase Postgres)
-- Apply in Supabase SQL editor (or migration pipeline) before enabling runtime sync endpoints.

create extension if not exists pgcrypto;

create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  display_name text,
  role text,
  approval text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists clients (
  id text primary key,
  name text not null,
  facility_type text,
  facility_status text,
  contract_type text,
  open_tickets integer not null default 0,
  city text,
  group_name text,
  facilities_relation_ids text[] not null default '{}',
  source text not null default 'monday',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists facilities (
  id text primary key,
  client_id text references clients(id) on delete set null,
  name text not null,
  facility_type text,
  facility_status text,
  contract_type text,
  open_tickets integer not null default 0,
  city text,
  group_name text,
  source text not null default 'monday',
  raw_columns jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists operations (
  id text primary key,
  short_operation_id text,
  client_id text references clients(id) on delete set null,
  facility_id text references facilities(id) on delete set null,
  assigned_technician_email text,
  business_status text,
  operation_group_status text,
  execution_status text,
  source text not null default 'monday',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists assignments (
  id uuid primary key default gen_random_uuid(),
  operation_id text references operations(id) on delete cascade,
  user_email text,
  technician_name text,
  role text,
  valid_from timestamptz,
  valid_to timestamptz,
  source text not null default 'monday',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists schedule_entries (
  id text primary key,
  operation_id_ref text,
  operation_id text references operations(id) on delete set null,
  technician_email text,
  schedule_control_status text,
  calendar_sync_status text,
  calendar_event_id text,
  report_item_id_ref text,
  source text not null default 'monday',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists reports (
  id text primary key,
  operation_id_ref text,
  operation_id text references operations(id) on delete set null,
  schedule_entry_id_ref text,
  schedule_entry_id text references schedule_entries(id) on delete set null,
  technician_email text,
  flow_status text,
  qa_status text,
  executed_at timestamptz,
  source text not null default 'monday',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists exceptions (
  id bigint generated by default as identity primary key,
  code text not null,
  severity text not null,
  operation_id text,
  schedule_entry_id text,
  report_id text,
  technician_email text,
  message text not null,
  source text not null default 'runtime',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists sync_runs (
  id bigint generated by default as identity primary key,
  source text not null,
  status text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  rows_upserted integer not null default 0,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists raw_events (
  id bigint generated by default as identity primary key,
  source text not null,
  event_type text not null,
  entity_id text,
  payload jsonb not null,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  sync_run_id bigint references sync_runs(id) on delete set null
);

create table if not exists agent_actions (
  id bigint generated by default as identity primary key,
  actor_email text,
  action_type text not null,
  target_entity_type text,
  target_entity_id text,
  input_payload jsonb not null default '{}'::jsonb,
  output_payload jsonb not null default '{}'::jsonb,
  status text not null default 'created',
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists idx_operations_short_id on operations(short_operation_id);
create index if not exists idx_operations_technician_email on operations(assigned_technician_email);
create index if not exists idx_schedule_operation_ref on schedule_entries(operation_id_ref);
create index if not exists idx_schedule_technician_email on schedule_entries(technician_email);
create index if not exists idx_reports_operation_ref on reports(operation_id_ref);
create index if not exists idx_reports_schedule_ref on reports(schedule_entry_id_ref);
create index if not exists idx_reports_technician_email on reports(technician_email);
create index if not exists idx_exceptions_code on exceptions(code);
create index if not exists idx_exceptions_operation_id on exceptions(operation_id);
create index if not exists idx_raw_events_source_event_type on raw_events(source, event_type);
create index if not exists idx_sync_runs_source_started on sync_runs(source, started_at desc);



